# NOTE: anything in same dir is part of the image.
FROM debian:jessie
MAINTAINER Amber Higgins <amhiggin@tcd.ie>

# Fix uid/gid to 1000 for shared volumes
RUN groupadd -r -g 1000 cowrie && \
    useradd -r -g 1000 -d /cowrie -m -g cowrie cowrie

# Set up env dependencies
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y \
        -o APT::Install-Suggests=false \
        -o APT::Install-Recommends=false \
      python-pip \
      openssh-server \
      libssl-dev \
      libffi-dev \
      build-essential \
      libpython-dev \
      python2.7-minimal \
      git \
      openssh-server \
      virtualenv \
      python-virtualenv \
      authbind \
      python-setuptools

# TO BE REMOVED
RUN apt-get install -y \
      nmap \
      traceroute \
      net-tools

# Set up SSH on cowrie
#RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
#    echo "export VISIBLE=now" >> /etc/profile && \
#    service ssh restart
#service sshd restart


# Build the environment for cowrie
RUN su - cowrie -c "\
     git clone http://github.com/micheloosterhof/cowrie /cowrie/cowrie-git && \
      cd /cowrie/cowrie-git && \
        virtualenv cowrie-env && \
        . cowrie-env/bin/activate && \
        pip install --upgrade pip && \
        pip install --upgrade cffi && \
        pip install --upgrade setuptools && \
        pip install --upgrade -r /cowrie/cowrie-git/requirements.txt"

# Allow cowrie to listen as non-root on ports 22 and 23
#RUN touch /etc/authbind/byport/22 && \
#    touch /etc/authbind/byport/23 && \
#    chown cowrie:cowrie /etc/authbind/byport/22 && \
#    chown cowrie:cowrie /etc/authbind/byport/23 && \
#    chmod 777 /etc/authbind/byport/22 && \
#    chmod 777 /etc/authbind/byport/23
#RUN sed -i 's/AUTHBIND_ENABLED=no/AUTHBIND_ENABLED=yes/' /cowrie/cowrie-git/bin/cowrie

COPY /cowrie/start.sh /cowrie/cowrie-git/start.sh
RUN chmod +rx /cowrie/cowrie-git/start.sh && \
    echo "Copied script and ran permission changes"

# CONFIGURATION
WORKDIR /cowrie/cowrie-git
RUN chown cowrie /cowrie/cowrie-git/log
ENTRYPOINT "/cowrie/cowrie-git/start.sh"
#CMD ["sleep", "infinity"]
EXPOSE 22 23
VOLUME ["/cowrie/cowrie-git/log/tty", "/cowrie/cowrie-git/data", "/cowrie/cowrie-git/dl", "/cowrie/cowrie-git/etc"]
