# NOTE: anything in same dir is part of the image.
FROM debian:jessie
MAINTAINER Amber Higgins <amhiggin@tcd.ie>

# Fix uid/gid to 1000 for shared volumes
RUN groupadd -r -g 1000 cowrie && \
    useradd -r -g 1000 -d /cowrie -m -g cowrie cowrie

# Set up env dependencies
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y \
        -o APT::Install-Suggests=false \
        -o APT::Install-Recommends=false \
      python-pip \
      libssl-dev \
      libffi-dev \
      build-essential \
      libpython-dev \
      python2.7-minimal \
      git \
      openssh-server \
      virtualenv \
      python-virtualenv \
      authbind \
      python-setuptools

# TO BE REMOVED
RUN apt-get install -y \
      nmap \
      traceroute \
      net-tools \
      iptables


# Build the environment for cowrie
RUN su - cowrie -c "\
     git clone http://github.com/micheloosterhof/cowrie /cowrie/cowrie-git && \
      cd /cowrie/cowrie-git && \
        virtualenv cowrie-env && \
        . cowrie-env/bin/activate && \
        pip install --upgrade pip && \
        pip install --upgrade cffi && \
        pip install --upgrade setuptools && \
        pip install --upgrade -r /cowrie/cowrie-git/requirements.txt"

COPY /cowrie/start.sh /cowrie/cowrie-git/start.sh
RUN chmod +rx /cowrie/cowrie-git/start.sh && \
    echo "Copied script and ran permission changes"

# CONFIGURATION
WORKDIR /cowrie/cowrie-git
RUN chown cowrie /cowrie/cowrie-git/log
ENTRYPOINT "/cowrie/cowrie-git/start.sh"
VOLUME ["/cowrie/cowrie-git/log/tty", "/cowrie/cowrie-git/data", "/cowrie/cowrie-git/dl", "/cowrie/cowrie-git/etc"]
