# NOTE: anything in same dir is part of the image.
FROM ubuntu:latest
MAINTAINER Amber Higgins <amhiggin@tcd.ie>

# Fix uid/gid to 1000 for shared volumes
RUN groupadd -r -g 1000 cowrie && \
    useradd -r -g 1000 -d /cowrie -m -g cowrie cowrie

# Set up env dependencies
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y \
        -o APT::Install-Suggests=false \
        -o APT::Install-Recommends=false \
      python-pip \
      libssl-dev \
      libffi-dev \
      build-essential \
      libpython-dev \
      python2.7-minimal \
      git \
      virtualenv \
      python-virtualenv \
      python-setuptools \
      net-tools \
      busybox \ 
      iptables

# Build the environment for cowrie
RUN su - cowrie -c "\
      git clone http://github.com/micheloosterhof/cowrie /cowrie/cowrie-git && \
      cd /cowrie/cowrie-git && \
        virtualenv cowrie-env && \
        . cowrie-env/bin/activate && \
        pip install --upgrade cffi && \
        pip install --upgrade pip && \
        pip install --upgrade setuptools && \
        pip install -r ~cowrie/cowrie-git/requirements.txt" 


# CONFIGURATION
USER cowrie
WORKDIR /cowrie/cowrie-git
CMD [ "/cowrie/cowrie-git/bin/cowrie", "start", "-n" ]
EXPOSE 22 23
VOLUME ["/cowrie/cowrie-git/log/tty", "/cowrie/cowrie-git/data", "/cowrie/cowrie-git/dl"]

# Change the permissions for log directory to persist them on host
RUN chown cowrie /cowrie/cowrie-git/log
