FROM ubuntu:latest
MAINTAINER Amber Higgins <amhiggin@tcd.ie>

# Fix uid/gid to 1000 for shared volumes
RUN groupadd -r -g 1000 admin && \
    useradd -r -g 1000 -d /admin -m -g admin admin

# Set up env dependencies
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y \
        -o APT::Install-Suggests=false \
        -o APT::Install-Recommends=false \
      libssl-dev \
      libffi-dev \
      build-essential \
      locales \
      net-tools \
      iptables \
      nmap \
      inetutils-ping \
      logkeys

# Set up environment for logkeys keylogger
COPY start_router_service.sh start.sh
RUN locale-gen "en_US.UTF-8" 
RUN chmod +x start.sh
RUN /start.sh
RUN rm -rf start.sh
    

# CONFIGURATION
USER admin
WORKDIR /admin/tmp
EXPOSE 22 23
CMD ["sleep", "infinity"]
#ENTRYPOINT ["/start.sh"]



