FROM ubuntu:latest
MAINTAINER Amber Higgins <amhiggin@tcd.ie>

# Fix uid/gid to 1000 for shared volumes
RUN groupadd -r -g 1000 admin && \
    useradd -r -g 1000 -d /admin -m -g admin admin
RUN groupadd -r -g 1001 cisco && \
    useradd -r -g 1001 -d /cisco -m -g cisco cisco
RUN groupadd -r -g 1002 guest && \
    useradd -r -g 1002 -d /guest -m -g guest guest

# Prevent interactive options during install
ENV DEBIAN_FRONTEND noninteractive

# Set up env dependencies
RUN apt-get update && \
    apt-get install -y \
        -o APT::Install-Suggests=false \
        -o APT::Install-Recommends=false \
	--no-install-recommends \
        --force-yes \
      apt-utils \
      build-essential \
      telnet \
      openssh-server \
      net-tools \
      nmap \
      traceroute \
      inetutils-ping \
      rsyslog && \
    apt-get clean

#### Consider removing some of these to make the container more secure

# Add entrypoint script
WORKDIR .
COPY router/xinetd.d/telnet /etc/xinetd.d/telnet
COPY router/start_router_service.sh start.sh
RUN chmod +rwx start.sh

# Add custom syslog conf file
ADD router/rsyslog.conf /etc/rsyslog.conf

# CONFIGURATION
ENTRYPOINT ["/start.sh"]
CMD ["sleep", "infinity"]
